### ISSUE TITLE
getting an error 

### ISSUE THREAD

**Issue by vucevic** [pranurs/fractal-dimensions#1]
I'm trying out the code (on one of my grey scale jpg image) to create grid lines and i'm getting an error that there is not enough input arguments in line: 
function [] = drawgrid(image, boxwidth)

**Comment by pranurs** [comment]
Hi! Thanks for reaching out. The `drawgrid` function expected a 3-channel image as input. I'm guessing maybe that's what has caused the error when you were trying to run it on a single channel image. Unfortunately one of the comments in that file was incorrectly put. I've fixed it such that the function now runs on single channel images too. The final saved image (with magenta grid lines), is a 3 channel image however, and this was done solely to allow the grid lines to be clearly visible (not just black). Please check it out and let me know if that solved the issue. Cheers!

**Comment by vucevic** [comment]
Hi,
Thanks for your response.
I'm having issues with boxwidth, i'm getting an error that it is an undefinded variable. Is there a way to specify the boxwidth I want - I've tried just replacing boxwidth with a number, and it still is not working.

What do you suggest I do?

Thanks,
Diana
________________________________

**Comment by pranurs** [comment]
The command I'm running on MATLAB's command window after navigating to the directory containing the script `drawgrid.m` is `drawgrid('img/koch-curve.png', 32)`. Here, the first argument can be replaced by the image file name and the second argument, by the boxwidth in pixels. This command is working for me. Is there any difference in the way you're calling it?

**Comment by pranurs** [comment]
@vucevic do let me know if the issue is resolved or if you're still facing a problem. Thanks!

**Comment by pranurs** [comment]
Issue closed due to inactivity. Do feel free to let me know if it still persists.

**Comment by malleswar22** [comment]
Hi I'm trying execute the python code for grey scale geo tif. But I'm getting an error of "image index out of range.

at 

 File "/Users/sai/untitled6.py", line 73, in <module>
    Ns = dbc(image, int(S))

  File "/Users/sai/untitled6.py", line 41, in dbc
    if pixel[k, l] > maxg:

IndexError: image index out of range


please help.

**Comment by pranurs** [comment]
Hi,

Are you still facing a problem? If so, please send me additional details so
that I can look into it.
